# Generated by Django 5.2.5 on 2025-08-27 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='auto',
            new_name='vino',
        ),
    ]
