# Generated by Django 5.2.5 on 2025-08-28 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_rename_auto_vino'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vino',
            old_name='modelo',
            new_name='año',
        ),
    ]
