# Generated by Django 5.2.5 on 2025-08-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_rename_modelo_vino_año'),
    ]

    operations = [
        migrations.AddField(
            model_name='vino',
            name='cantidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
